apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "wordpress123"
          - name:  MYSQL_DATABASE
            value: "wordpress"
          - name: MYSQL_USER
            value: "wordpress123"
          - name: WORDPRESS_DB_NAME
            value: "wordpress123"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        
